config/routes.rb
Bbook::Application.routes.draw do
  resources :profiles

  resources :mybook, :only =>[:index]

  resources :home, :only => [:index]
  namespace :admin do
    get '/' => "log#index"
    resources :log, :only => [:index]
    resources :user, :only => [:index]
    resources :new, :only => [:index]
  end
  devise_for :users, :controllers => {:registrations => "registrations"}

root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,  :idcard
  # attr_accessible :title, :body
  
  validates :password, :length => { :minimum => 6 }
  validates :password, :confirmation => true
  validates :email, :uniqueness => true
  validates :idcard, :uniqueness => true
  has_one :profile
end

app/controllers/admin/log_controller.rb
class Admin::LogController < ApplicationController
  def index
  end
end

app/controllers/admin/new_controller.rb
class Admin::NewController < ApplicationController
  def index
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mybook_controller.rb
class MybookController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource
    puts "-----------------------------------"
    puts params.inspect
    if resource.save
      #resource.update_attributes(:idcard => params[:idcard])
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mybooks_helper.rb
module MybooksHelper
end

app/views/admin/_admin_task_navbar.html.haml
.span3.well
  %ul{:class => "nav nav-list"}
    %li{:class => "nav-header"}
      Admin Task
    %li{:class => "divider"}
    %li{:class => "#{params["controller"] == "admin/log"? "active":""}"}
      = link_to "View logs",admin_log_index_path
    %li{:class => "#{params["controller"] == "admin/user"? "active":""}"}
      = link_to "User",admin_user_index_path
    %li{:class => "#{params["controller"] == "admin/new"? "active":""}"}
      = link_to "News",admin_new_index_path

app/views/admin/log/index.html.haml
.admin-task-content.row
  .span11.offset1
    = render 'admin/admin_task_navbar'
    .admin-task-body.span7.box-model2
      %p
        \  
        %table{:border => "1", :width => "690"}
          %td asdf

app/views/admin/new/index.html.haml
.mybook-page.row
  .span11.offset1
    = render "/admin/admin_task_navbar"
    .admin-task-body.span7.box-model2

app/views/admin/user/index.html.haml
.admin-task-content.row
  .span11.offset1
    = render "/admin/admin_task_navbar"
    .admin-task-body.span7.box-model2

app/views/home/_home_content.html.haml
.span11.offset1 
  .navbar.navbar-inner.main-menu-navs
    %ul{:class => "nav pull-right"}
      %li
        = link_to "Books", "#"
      %li{:class=> "divider-vertical"}
      %li
        = link_to "FAQ", "#"
      %li{:class=> "divider-vertical"}
      %li
        = link_to "About Us", "#"
    = form_tag "", :class => "navbar-search pull-left" do
      = text_field_tag "", nil, :class => "search-query span3", :placeholder => "Book Search"
.row
  .span11.offset1
    .container-fluid
      .span3.box-model
        a
      .span3.box-model
        b
      .span4.box-model
        new

app/views/home/index.html.haml
.home-pictures-carousel.carousel.slide#home-pics
  .carousel-inner
    .active.item
      = image_tag "pic1.jpg", :class => "img-rounded"
    .item
      = image_tag "pic3.jpg", :class => "img-rounded"
    .item
      = image_tag "pic2.jpg", :class => "img-rounded"
    .item
      = image_tag "pic4.jpg", :class => "img-rounded"  
  = link_to "<", "#home-pics", :class => "carousel-control left", "data-slide"=> "prev"
  = link_to ">", "#home-pics", :class => "carousel-control right", "data-slide"=> "next"
= render('home_content')
= javascript_tag do
  :erb
    $('.carousel').carousel({
      interval: 2000000
    });
  

app/views/layouts/_head_nav_bar.html.haml
.navbar-inner.nav-bar-edited
  %ul{:class => "nav pull-right"}
    %li.logo
      = link_to(image_tag("logo.png",:size => "40x25"),  root_path)
    - if !user_signed_in? 
      %li 
        = link_to "Login", new_user_session_path
      %li 
        = link_to "Signup", new_user_registration_path 
    - else
      %li
        = link_to "Hi, #{current_user.email.split('@')[0]}!", "#{current_user.profile ? edit_profile_path(current_user.profile) : new_profile_path}"
      %li
        = link_to "#" do
          %i{:class => "icon-envelope"}
      %li
        = link_to "My Books", mybook_index_path
      %li
        = link_to "Sign out", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  %title 
    BBooks
  %body
    .logo-header-bar.navbar.navbar-inverse.navbar-fixed-top
      = render '/layouts/head_nav_bar'
    .content-page-tag
      - if flash[:alert]
        .notification.alert.alert-info
          %strong 
            = flash[:alert]
          %button{:class => "close", "data-dismiss" => "alert"}x
      = yield()
  %footer{:class => "footer"}
    .footer-content.container
      %p 
        = link_to "Copyright 2012", "#"
      %p Design by Tran Duy Khoa

app/views/mybook/_form.html.haml
= form_for @mybook do |f|
  - if @mybook.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mybook.errors.count, "error")} prohibited this mybook from being saved:"
      %ul
        - @mybook.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/mybook/_head_tab.html.haml
.span3.well
  %ul{:class => "nav nav-list"}
    %li{:class => "nav-header"}
      My books task
    %li{:class => "divider"}
    %li{:class => "active"}
      = link_to "Borrowing","#"
    %li
      = link_to "Reserve","#"
    %li
      = link_to "All read","#"
    %li
      = link_to "Favorite","#"

app/views/mybook/index.html.haml
.mybook-page.row
  .span11.offset1
    = render "head_tab"
    .span7.box-model2